@extends('ecommerce.navbar')

@section('content')

    <div class="mt-24 font-bold p-12 text-violet-700">
      <div class="mb-10"><h2 class="text-2xl text-center">ABOUT US</h2></div>
      <div class="md:p-12">
        <div><h2 class="underline text-violet-700 md:text-lg">MISSION<i class="fa-solid fa-scroll fa-beat-fade ml-1 text-amber-500"></i></h2></div>
        <div class="text-sm md:text-lg mt-2">
          TO PROVIDE HIGH QUALITY PRODUCTS AND UNCONDITIONAL CUSTOMER
          SATISFACTION THAT PROMOTES A HEALTHIER, SAFER, CLEANER ENVIRONMENT
          AND MEETING CUSTOMER DEMANDS AND EXPECTATIONS DRIVEN BY CONTINOUS
          RESEARCH AND PRODUCT INNOVATIONS. WE ARE COMMITED TO DELIVERING
          ECO-FRIENDLY AND EFFECTIVE SOLUTIONS WHILE MINIMIZING THE IMPACT
          ON THE PLANET DEVELOPMENT.
        </div>
      </div>
      <br>
      <hr>
      <hr>
      <br>

      <div class="md:p-12">
        <div><h2 class="underline text-violet-700 md:text-lg">VISION<i class="fa-solid fa-eye fa-shake ml-1 text-amber-500"></i></h2></div>
        <div class="text-sm md:text-lg mt-2">
          DRIVEN BY OUR PASSION FOR CLEANLINESS AND ENVIRONMENTAL
          STEWARDSHIP, WE ARE AIMING TO BECOME THE MOST TRUSTED AND ADMIRED
          BRAND FOR HOMECARE PRODUCTS WORLDWIDE. WE ENVISION A FUTURE WHERE
          OUR INNOVATIVE AND ECO-FRIENDLY SOLUTIONS ARE SYNONYMOUS WITH
          CLEANLINESS AND HYGIENE, SETTING THE BENCHMARK FOR THE INDUSTRY.
          BY FOSTERING A CULTURE OF EXCELLENCE, SUSTAINABILITY, AND
          CONTINUOUS IMPROVEMENT, WE AIM TO INSPIRE AND EMPOWER INDIVIDUALS
          AND BUSINESSES TO EMBRACE A CLEANER AND HEALTHIER LIFESTYLE,
          MAKING A POSITIVE IMPACT ON THE WELL-BEING OF PEOPLE AND THE
          PLANET.
        </div>
      </div>

    </div>   

@endsection

{{-- TO PROVIDE HIGH QUALITY PRODUCTS AND UNCONDITIONAL CUSTOMER
SATISFACTION THAT PROMOTES A HEALTHIER, SAFER, CLEANER ENVIRONMENT
AND MEETING CUSTOMER DEMANDS AND EXPECTATIONS DRIVEN BY CONTINOUS
RESEARCH AND PRODUCT INNOVATIONS. WE ARE COMMITED TO DELIVERING
ECO-FRIENDLY AND EFFECTIVE SOLUTIONS WHILE MINIMIZING THE IMPACT
ON THE PLANET DEVELOPMENT.

DRIVEN BY OUR PASSION FOR CLEANLINESS AND ENVIRONMENTAL
STEWARDSHIP, WE ARE AIMING TO BECOME THE MOST TRUSTED AND ADMIRED
BRAND FOR HOMECARE PRODUCTS WORLDWIDE. WE ENVISION A FUTURE WHERE
OUR INNOVATIVE AND ECO-FRIENDLY SOLUTIONS ARE SYNONYMOUS WITH
CLEANLINESS AND HYGIENE, SETTING THE BENCHMARK FOR THE INDUSTRY.
BY FOSTERING A CULTURE OF EXCELLENCE, SUSTAINABILITY, AND
CONTINUOUS IMPROVEMENT, WE AIM TO INSPIRE AND EMPOWER INDIVIDUALS
AND BUSINESSES TO EMBRACE A CLEANER AND HEALTHIER LIFESTYLE,
MAKING A POSITIVE IMPACT ON THE WELL-BEING OF PEOPLE AND THE
PLANET. --}}